# Generated by Django 5.1.2 on 2024-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sunset", models.TimeField()),
                ("sunrise", models.TimeField()),
                ("date", models.DateField()),
                ("country", models.CharField(default="Paris", max_length=255)),
            ],
        ),
    ]
