# Generated by Django 5.1.2 on 2024-11-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sun", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sunset", models.TimeField()),
                ("sunrise", models.TimeField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="sun",
            name="date",
        ),
        migrations.RemoveField(
            model_name="sun",
            name="sunrise",
        ),
        migrations.RemoveField(
            model_name="sun",
            name="sunset",
        ),
        migrations.AddField(
            model_name="sun",
            name="hours",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sun.hour"
            ),
        ),
    ]
